Base:
    model_root: './checkpoints/'
    num_workers: 8
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

TF4CTR_Criteo_10:
    model: TF4CTRv2
    dataset_id: Criteo_x4_10_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    hard_hidden_units: [400, 400, 400]
    easy_hidden_units: [400, 400]
    gamma: 2
    c: 0.8
    alpha: 0.25
    SSM: SER
    DFM: WSF
    hidden_activations: relu
    net_dropout: 0.2
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': 0}
    monitor_mode: 'max'