base_config: ./config/
base_expid: TF4CTR_Criteo_10
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    hard_hidden_units: [[400, 400, 400]]
    easy_hidden_units: [[400, 400]]
    gamma: [2]
    c: [0.9, 0.8, 0.7, 0.6, 0.5]
    alpha: [0.1, 0.2, 0.3, 0.4]
    net_dropout: [0.2]
    seed: 2023

