base_config: ./config/
base_expid: TF4CTRv2_Criteo_10
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    SSM: [ SER ]
    DFM: [ WSF ]
    easy_hidden_units: [ [ 400, 400 ], [400] ]
    gamma: [ 1, 2, 3 ]
    c: [ 0.7, 0.8, 0.9 ]
    alpha: [0.15, 0.25, 0.35]
    net_dropout: [0.1, 0.2, 0.3]

